#!/bin/bash

# Copyright (c) 2012, Jan Friesse <jfriesse@gmail.com>
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

br_var=kvm_bridge_$1
br='$'`echo "$br_var"`
br=`eval echo $br`

[ "$br" == "" ] && echo "No bridge found!" && exit 1
if [ -n "$1" ];then
    /sbin/ifconfig "$1" up || exit 1
    sleep 1
    /usr/sbin/brctl addif "$br" $1 || exit 1

    exit 0
else
    echo "Error: no interface specified"
    exit 1
fi
